lusid-sdk-python/tests/api_client_builder.py
lusid-sdk-python/tests/finbournetest.py
lusid-sdk-python/tests/test_finbourne_client.py
lusid-sdk-python/tests/tutorials/test_portfolios_transactions.py

DEV-3048 Add tutorial samples

---

sdk/tests/tutorials/ibor/test_cut_labels.py
sdk/tests/utilities/test_data_utilities.py

Describe the code changes for the reviewers, explain the solution you have provided and how it fixes the issue case

DEV-4639 : add cut labels example and update test data utilities

---

sdk/tests/tutorials/marketdata/test_instruments.py

DEV-4494 API changes for UpsertInstrumentsProperties

---

sdk/tests/tutorials/ibor/test_properties.py
sdk/tests/tutorials/ibor/test_transactions.py

Added [EARLY ACCESS] tests to ensure parity with c# sdk. 
+ added test_properties()
+ added test_create_portfolio_with_label_property()
+ added test_create_portfolio_with_metric_property()
- edited test_transactions.py
+ added test_cancel_transactions()

DEV-4904 added tests to test_properties.py and test_transactions.py

---

sdk/lusid/__init__.py
sdk/lusid/utilities/__init__.py
sdk/lusid/utilities/api_client_builder.py
sdk/lusid/utilities/api_configuration.py
sdk/lusid/utilities/api_configuration_loader.py
sdk/lusid/utilities/refreshing_token.py
sdk/tests/test_token_refresh.py
sdk/tests/tutorials/ibor/test_bitemporal.py
sdk/tests/tutorials/ibor/test_cut_labels.py
sdk/tests/tutorials/ibor/test_holdings.py
sdk/tests/tutorials/ibor/test_portfolios.py
sdk/tests/tutorials/ibor/test_properties.py
sdk/tests/tutorials/ibor/test_reconciliation.py
sdk/tests/tutorials/ibor/test_transactions.py
sdk/tests/tutorials/marketdata/test_instruments.py
sdk/tests/utilities/__init__.py
sdk/tests/utilities/test_data_utilities.py

DEV-4647 Added the SDK refresh logic to the client

---

sdk/tests/tutorials/ibor/test_portfolios.py
sdk/tests/tutorials/ibor/test_properties.py
sdk/tests/tutorials/ibor/test_transactions.py

TR-282: Fix API funcs

---

sdk/tests/utilities/test_data_utilities.py

- [x ] Read the [contributing guidelines](https://github.com/finbourne/lusid-sdk-python-preview/blob/master/CONTRIBUTING.md)
- [ x] Tests pass
- [ x] Raised the PR against the `develop` branch

DEV-5333 Update body parameter for create portfolio

---

sdk/setup.py

- [x ] Read the [contributing guidelines](https://github.com/finbourne/lusid-sdk-python-preview/blob/master/CONTRIBUTING.md)
- [x ] Tests pass
- [ x] Raised the PR against the `develop` branch

DEV-7126 Update REQUIRES in Setup.py to match requirements.txt

---

sdk/tests/tutorials/ibor/test_bitemporal.py
sdk/tests/tutorials/ibor/test_cut_labels.py
sdk/tests/tutorials/ibor/test_holdings.py
sdk/tests/tutorials/ibor/test_portfolios.py
sdk/tests/tutorials/ibor/test_properties.py
sdk/tests/tutorials/ibor/test_reconciliation.py
sdk/tests/tutorials/ibor/test_transactions.py
sdk/tests/utilities/instrument_loader.py
sdk/tests/utilities/test_data_utilities.py

DEV-8417 OA3 update changes

---

sdk/tests/tutorials/ibor/test_transactions.py
sdk/tests/tutorials/marketdata/test_instruments.py

DEV-9094 : remove custom OTC instrument tests pending replacement

---

sdk/tests/tutorials/ibor/test_reference_portfolios.py

Add test for F39 to release SDK

---

sdk/lusid/__init__.py

This PR will add the ApiClientFactory to the module-level imports.

SE-1065: Add ApiClientFactory to module imports

---

README.md
sdk/examples/hello_world.py
sdk/setup.py

- Added link for 30-day free trial
- Added Hello World example + link to tutorial explaining how to setup secrets file
- Shrunk the logo a bit
- In-lined instructions for how to generate the SDK yourself

Readme refactoring

---

.readthedocs.yaml
docs/Makefile
docs/README.md
docs/_static/pydata-custom.css
docs/_static/readthedocs-custom.css
docs/_templates/custom-class-template.rst
docs/_templates/custom-module-template.rst
docs/api.rst
docs/conf.py
docs/index.rst
docs/make.bat
docs/requirements.txt

As per title. HTML doc should be automatically generated on commit to master and published to Readthedocs.org (for now; this location can be changed subsequently).

Sphinx setup for generating LUSID Python SDK HTML doc

---

sdk/lusid/tcp/tcp_keep_alive_probes.py

This code ensures that KeepAlive is used on Linux.
Needs further testing in a Jupyter environment to avoid regression.

Ensure KeepAlive is used on Linux (may break JupyterHub)

---

sdk/requirements.txt

Reverts finbourne/lusid-sdk-python#87

Revert "add simplejson"

---

sdk/requirements.txt

add simplejson

---

sdk/setup.py

Revert "Update setup.py"

---

sdk/tests/tutorials/ibor/test_bitemporal.py
sdk/tests/tutorials/ibor/test_cut_labels.py
sdk/tests/tutorials/ibor/test_holdings.py
sdk/tests/tutorials/ibor/test_portfolios.py
sdk/tests/tutorials/ibor/test_properties.py
sdk/tests/tutorials/ibor/test_reconciliation.py
sdk/tests/tutorials/ibor/test_reference_portfolios.py
sdk/tests/tutorials/ibor/test_transactions.py
sdk/tests/tutorials/marketdata/test_instruments.py

Migrated legacy labels of features in the python SDK to labels that reflect logical groupings e.g portfolios, instruments etc.

Reformatted features

---

sdk/lusid/utilities/lusid_retry.py
sdk/tests/utilities/test_retry.py

Fix retry-after when str
Bring utilities to parity with preview

CTECH-1098 fix try when str

---

sdk/tests/tutorials/ibor/test_cut_labels.py

CTECH-1213 handle duplicate cut labels

---

sdk/docker-compose.yml
sdk/lusid/utilities/api_client_builder.py
sdk/lusid/utilities/api_client_factory.py
sdk/lusid/utilities/api_configuration.py
sdk/lusid/utilities/api_configuration_loader.py
sdk/lusid/utilities/config_keys.json
sdk/lusid/utilities/refreshing_token.py
sdk/tests/tutorials/ibor/test_portfolios.py
sdk/tests/utilities/__init__.py
sdk/tests/utilities/credentials_source.py
sdk/tests/utilities/id_generator.py
sdk/tests/utilities/id_generator_utilities.py
sdk/tests/utilities/instrument_loader.py
sdk/tests/utilities/mock_api_response.py
sdk/tests/utilities/test_api_client_builder.py
sdk/tests/utilities/test_api_client_factory.py
sdk/tests/utilities/test_api_client_factory_auth_flow.py
sdk/tests/utilities/test_api_configuration.py
sdk/tests/utilities/test_api_configuration_loader.py
sdk/tests/utilities/test_data_utilities.py
sdk/tests/utilities/test_id_generator.py
sdk/tests/utilities/test_token_refresh.py
sdk/tests/utilities/token_utilities.py

Update sdk utilities to be inline with preview sdk

CTECH-1116 update utilities

---

sdk/lusid/utilities/refreshing_token.py
sdk/tests/utilities/test_token_refresh.py

CTECH-1461 support special characters in secrets

---

sdk/requirements.txt
sdk/setup.py

Signed-off-by: Paul Saunders <pms1969@gmail.com>
Adds dependency for non-lusid sdks.

CTECH-1344: Adds fbnsdkutilities as a dependency

---

sdk/requirements.txt

Signed-off-by: Paul Saunders <paul.saunders@finbourne.com>
test failures require the removal of this package.

CTECH-1344: Removes dependency that is causing test failures.

---

sdk/Dockerfile
sdk/lusid/utilities/__init__.py
sdk/lusid/utilities/config_keys.py
sdk/requirements.txt
sdk/tests/utilities/test_api_client_factory_auth_flow.py

Add config_keys so we can build  apiclient in fbnsdkutilities

CTECH-2527: Add config_keys

---

.readthedocs.yaml
docs/conf.py

Fix for Readthedocs build config change
